name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v6

      - id: setup-dotnet
        name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "npm"

      - id: install-deps
        name: Install dependencies
        run: npm ci

      - id: install-web-deps
        name: Install web dependencies
        run: npm ci --prefix src/web

      - id: restore-dotnet
        name: Restore .NET
        run: dotnet restore my-api-v3.sln

      - id: lint
        name: Lint
        run: npm run lint

      - id: build
        name: Build
        run: npm run build

      - id: unit-tests
        name: Unit tests
        run: npm run test

      - id: install-playwright
        name: Install Playwright browsers
        run: npx playwright install chromium --with-deps
        working-directory: src/web

      - id: e2e-tests
        name: E2E tests
        run: npm run test:e2e
        env:
          CI: true
